tiny-mesh-viewer: tiny_mesh_viewer::scene::TriMesh Class Reference
tiny_mesh_viewer::scene::TriMesh Class Reference
#include <tri_mesh.h>
Classes
struct Vertex
Public Types
using MyMesh = OpenMesh::TriMesh_ArrayKernelT<>
Public Member Functions
virtual ~TriMesh ()=default
virtual void Draw () override
virtual void Load () override
Create OpenGL object and copy data to buffers.
glm::vec3 color () const
void set_color (const glm::vec3 color)
Public Member Functions inherited from tiny_mesh_viewer::scene::Object
Object (const glm::vec3 &position=kDefaultPosition, const glm::vec3 &rotation=kDefaultRotation, const glm::vec3 &translation_speed=kDefaultTranslationSpeed, const glm::vec3 &rotation_speed=kDefaultRotationSpeed)
virtual ~Object ()=default
virtual void Draw ()
virtual void Load ()
Create OpenGL object and copy data to buffers.
void Update (const float delta_time)
Update position & rotation.
glm::mat4 ModelView () const
glm::mat4 NormalMatrix () const
glm::vec3 position () const
void set_position (const glm::vec3 &position)
glm::vec3 rotation () const
void set_rotation (const glm::vec3 &rotation)
glm::vec3 translation_speed () const
void set_translation_speed (const glm::vec3 &translation_speed)
glm::vec3 rotation_speed () const
void set_rotation_speed (const glm::vec3 &rotation_speed)
shader::Shader & shader ()
void set_shader (std::shared_ptr< shader::Shader > shader)
std::string_view shader_id () const
void set_shader_id (const std::string_view shader_id)
Static Public Member Functions
static std::shared_ptr< TriMesh > FromYAML (const YAML::Node &yaml)
static std::shared_ptr< TriMesh > Read (const std::filesystem::path &filepath, const bool flip_normals=false)
Static Public Member Functions inherited from tiny_mesh_viewer::scene::Object
static std::shared_ptr< Object > FromYAML (const YAML::Node &yaml)
Private Attributes
std::vector< TriMesh::Vertex > vertices_
std::vector< unsigned > indices_
glm::vec3 color_ = kDefaultColor
std::unique_ptr< opengl::ArrayBuffer > array_buffer_
std::unique_ptr< opengl::ElementArrayBuffer > element_array_buffer_
std::unique_ptr< opengl::VertexArray > vertex_array_
Static Private Attributes
static constexpr glm::vec3 kDefaultColor
Additional Inherited Members
Protected Attributes inherited from tiny_mesh_viewer::scene::Object
glm::vec3 position_
glm::vec3 rotation_
glm::vec3 translation_speed_
glm::vec3 rotation_speed_
std::shared_ptr< shader::Shader > shader_
std::string shader_id_
Static Protected Attributes inherited from tiny_mesh_viewer::scene::Object
static constexpr glm::vec3 kDefaultPosition = glm::vec3(0.0, 0.0, 0.0)
static constexpr glm::vec3 kDefaultRotation = glm::vec3(0.0, 0.0, 0.0)
static constexpr glm::vec3 kDefaultTranslationSpeed
static constexpr glm::vec3 kDefaultRotationSpeed = glm::vec3(0.0, 0.0, 0.0)
Detailed Description
Definition at line 18 of file tri_mesh.h.
Member Typedef Documentation
MyMesh
using tiny_mesh_viewer::scene::TriMesh::MyMesh = OpenMesh::TriMesh_ArrayKernelT<>
Definition at line 20 of file tri_mesh.h.
Constructor & Destructor Documentation
~TriMesh()
virtual tiny_mesh_viewer::scene::TriMesh::~TriMesh () virtual default
Member Function Documentation
color()
glm::vec3 tiny_mesh_viewer::scene::TriMesh::color () const
Definition at line 72 of file tri_mesh.cc.
{ return this->color_; }
References color_.
Referenced by Draw(), and set_color().
Draw()
void tiny_mesh_viewer::scene::TriMesh::Draw () override virtual
Reimplemented from tiny_mesh_viewer::scene::Object.
Definition at line 22 of file tri_mesh.cc.
                   {
  if (!this->shader_) return;
  this->Object::Draw();
  auto with = common::WithUse(this->shader());
  this->shader().UniformVec3(/*name=*/"object_color", /*value=*/this->color());
  {
    auto with = common::WithBind(*(this->vertex_array_));
    glDrawElements(/*mode=*/GL_TRIANGLES, /*count=*/this->indices_.size(),
                   /*type=*/GL_UNSIGNED_INT, /*indices=*/nullptr);
  }
}
References color(), tiny_mesh_viewer::scene::Object::Draw(), indices_, tiny_mesh_viewer::scene::Object::shader(), tiny_mesh_viewer::scene::Object::shader_, tiny_mesh_viewer::opengl::Program::UniformVec3(), and vertex_array_.
FromYAML()
std::shared_ptr< TriMesh > tiny_mesh_viewer::scene::TriMesh::FromYAML (const YAML::Node & yaml) static
Definition at line 76 of file tri_mesh.cc.
{
  assert(yaml["type"].as<std::string>() == "TriMesh");
  bool flip_normals = yaml["flip_normals"].as<bool>(/*fallback=*/false);
  auto tri_mesh =
      TriMesh::Read(yaml["filepath"].as<std::string>(), flip_normals);
  tri_mesh->set_color(
      common::Config::AsVec3(yaml["color"], /*fallback=*/kDefaultColor));
  return tri_mesh;
}
References tiny_mesh_viewer::common::Config::AsVec3(), kDefaultColor, and Read().
Referenced by tiny_mesh_viewer::scene::Object::FromYAML().
Load()
void tiny_mesh_viewer::scene::TriMesh::Load () override virtual
Create OpenGL object and copy data to buffers.
Reimplemented from tiny_mesh_viewer::scene::Object.
Definition at line 34 of file tri_mesh.cc.
                   {
  this->array_buffer_ = std::make_unique<opengl::ArrayBuffer>();
  this->element_array_buffer_ = std::make_unique<opengl ::ElementArrayBuffer>();
  this->vertex_array_ = std::make_unique<opengl::VertexArray>();
  {
    auto with = common::WithBind(*(this->vertex_array_));
    {
      auto with = common::WithBind(*(this->array_buffer_));
      auto stride = sizeof(TriMesh::Vertex);
      this->array_buffer_->Data(
          /*size=*/this->vertices_.size() * stride,
          /*data=*/this->vertices_.data(),
          /*usage=*/GL_STATIC_DRAW);
      this->vertex_array_->VertexAttribPointer(
          /*index=*/0, /*size=*/3, /*type=*/GL_FLOAT,
          /*normalized=*/GL_FALSE,
          /*stride=*/stride,
          /*pointer=*/
          reinterpret_cast<void*>(offsetof(TriMesh::Vertex, position)));
      this->vertex_array_->EnableVertexAttribArray(/*index=*/0);
      this->vertex_array_->VertexAttribPointer(
          /*index=*/1, /*size=*/3, /*type=*/GL_FLOAT,
          /*normalized=*/GL_FALSE,
          /*stride=*/stride,
          /*pointer=*/
          reinterpret_cast<void*>(offsetof(TriMesh::Vertex, normal)));
      this->vertex_array_->EnableVertexAttribArray(/*index=*/1);
    }
    {
      auto with = common::WithBind(*(this->element_array_buffer_));
      this->element_array_buffer_->Data(
          /*size=*/this->indices_.size() * sizeof(int),
          /*data=*/this->indices_.data(), /*usage=*/GL_STATIC_DRAW);
    }
  }
}
References array_buffer_, element_array_buffer_, indices_, tiny_mesh_viewer::scene::Object::position(), vertex_array_, and vertices_.
Read()
std::shared_ptr< TriMesh > tiny_mesh_viewer::scene::TriMesh::Read (const std::filesystem::path & filepath, const bool flip_normals = false) static
Definition at line 86 of file tri_mesh.cc.
{
  TriMesh::MyMesh mesh;
  if (!OpenMesh::IO::read_mesh(mesh, /*filename=*/filepath)) {
    throw common::Exception<std::runtime_error>(
        /*loc=*/common::source_loc::current(),
        /*what=*/"read_mesh()");
  }
  mesh.request_face_normals();
  mesh.request_vertex_normals();
  mesh.update_normals();
  auto tri_mesh = std::make_shared<TriMesh>();
  std::transform(
      /*first=*/mesh.vertices_begin(),
      /*last=*/mesh.vertices_end(),
      /*result=*/std::back_inserter(tri_mesh->vertices_),
      /*unary_op=*/
      [&mesh, flip_normals](const TriMesh::MyMesh::VertexHandle vh) -> Vertex {
        return TriMesh::Vertex{
            .position = mesh.point(vh),
            .normal = flip_normals ? -mesh.normal(vh) : mesh.normal(vh),
        };
      });
  std::for_each(
      /*first=*/mesh.faces_begin(),
      /*last=*/mesh.faces_end(),
      /*f=*/
      [&mesh,
       &tri_mesh = *tri_mesh](const TriMesh::MyMesh::FaceHandle fh) -> void {
        std::for_each(
            /*first=*/mesh.fv_begin(fh),
            /*last=*/mesh.fv_end(fh),
            /*f=*/
            [&tri_mesh](const TriMesh::MyMesh::VertexHandle vh) -> void {
              tri_mesh.indices_.push_back(vh.idx());
            });
      });
  return tri_mesh;
}
Referenced by FromYAML().
set_color()
void tiny_mesh_viewer::scene::TriMesh::set_color (const glm::vec3 color)
Definition at line 74 of file tri_mesh.cc.
{ this->color_ = color; }
References color(), and color_.
Member Data Documentation
array_buffer_
std::unique_ptr<opengl::ArrayBuffer> tiny_mesh_viewer::scene::TriMesh::array_buffer_ private
Definition at line 46 of file tri_mesh.h.
Referenced by Load().
color_
glm::vec3 tiny_mesh_viewer::scene::TriMesh::color_ = kDefaultColor private
Definition at line 44 of file tri_mesh.h.
Referenced by color(), and set_color().
element_array_buffer_
std::unique_ptr<opengl::ElementArrayBuffer> tiny_mesh_viewer::scene::TriMesh::element_array_buffer_ private
Definition at line 47 of file tri_mesh.h.
Referenced by Load().
indices_
std::vector<unsigned> tiny_mesh_viewer::scene::TriMesh::indices_ private
Definition at line 43 of file tri_mesh.h.
Referenced by Draw(), and Load().
kDefaultColor
constexpr glm::vec3 tiny_mesh_viewer::scene::TriMesh::kDefaultColor static constexpr private
Initial value:
=
      glm::vec3(204.0 / 255.0, 102.0 / 255.0, 0.0)
Definition at line 50 of file tri_mesh.h.
Referenced by FromYAML().
vertex_array_
std::unique_ptr<opengl::VertexArray> tiny_mesh_viewer::scene::TriMesh::vertex_array_ private
Definition at line 48 of file tri_mesh.h.
Referenced by Draw(), and Load().
vertices_
std::vector<TriMesh::Vertex> tiny_mesh_viewer::scene::TriMesh::vertices_ private
Definition at line 42 of file tri_mesh.h.
Referenced by Load().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/scene/object/tri_mesh.h
tiny_mesh_viewer/scene/object/tri_mesh.cc