tiny-mesh-viewer: tiny_mesh_viewer::opengl::App Class Reference
tiny_mesh_viewer::opengl::App Class Reference
#include <app.h>
Public Member Functions
App ()
~App ()
void Enable (GLenum cap)
void Init ()
void LoadGLLoader (GLADloadproc proc)
void Terminate ()
Static Public Member Functions
static double GetTime ()
static void PollEvents ()
Detailed Description
Definition at line 8 of file app.h.
Constructor & Destructor Documentation
App()
tiny_mesh_viewer::opengl::App::App () explicit
Definition at line 13 of file app.cc.
{ this->Init(); }
References Init().
~App()
tiny_mesh_viewer::opengl::App::~App ()
Definition at line 15 of file app.cc.
{ this->Terminate(); }
References Terminate().
Member Function Documentation
Enable()
void tiny_mesh_viewer::opengl::App::Enable (GLenum cap)
Definition at line 17 of file app.cc.
{ glEnable(cap); }
Referenced by tiny_mesh_viewer::App::App().
GetTime()
double tiny_mesh_viewer::opengl::App::GetTime () static
Definition at line 36 of file app.cc.
{ return glfwGetTime(); }
Referenced by tiny_mesh_viewer::ui::Window::Run().
Init()
void tiny_mesh_viewer::opengl::App::Init ()
Definition at line 19 of file app.cc.
               {
  int ret = glfwInit();
  if (ret != GLFW_TRUE) {
    throw common::Exception<std::runtime_error>(
        /*loc=*/common::source_loc::current(), /*what=*/"glfwInit()");
  }
}
Referenced by App().
LoadGLLoader()
void tiny_mesh_viewer::opengl::App::LoadGLLoader (GLADloadproc proc)
Definition at line 27 of file app.cc.
{
  if (!gladLoadGLLoader(proc)) {
    throw common::Exception<std::runtime_error>(
        /*loc=*/common::source_loc::current(), /*what=*/"gladLoadGLLoader()");
  }
}
Referenced by tiny_mesh_viewer::App::App().
PollEvents()
void tiny_mesh_viewer::opengl::App::PollEvents () static
Definition at line 38 of file app.cc.
{ glfwPollEvents(); }
Referenced by tiny_mesh_viewer::ui::Window::Run().
Terminate()
void tiny_mesh_viewer::opengl::App::Terminate ()
Definition at line 34 of file app.cc.
{ glfwTerminate(); }
Referenced by ~App().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/opengl/app.h
tiny_mesh_viewer/opengl/app.cc