tiny-mesh-viewer: tiny_mesh_viewer::opengl::Program Class Reference
tiny_mesh_viewer::opengl::Program Class Reference
#include <program.h>
Public Member Functions
Program ()
~Program ()
template<GLenum shader_type>
void AttachShader (const Shader< shader_type > &shader)
void Link ()
void Use ()
void Unuse ()
void UniformFloat (const std::string_view name, const float value)
void UniformMat4 (const std::string_view name, const glm::mat4 &value)
void UniformVec3 (const std::string_view name, const glm::vec3 &value)
float GetUniformFloat (const std::string_view name) const
glm::mat4 GetUniformMat4 (const std::string_view name) const
glm::vec3 GetUniformVec3 (const std::string_view name) const
Private Attributes
GLuint id_
Detailed Description
Definition at line 13 of file program.h.
Constructor & Destructor Documentation
Program()
tiny_mesh_viewer::opengl::Program::Program () explicit
Definition at line 17 of file program.cc.
{ this->id_ = glCreateProgram(); }
References id_.
~Program()
tiny_mesh_viewer::opengl::Program::~Program ()
Definition at line 19 of file program.cc.
{ glDeleteProgram(/*program=*/this->id_); }
References id_.
Member Function Documentation
AttachShader()
template<GLenum shader_type> void tiny_mesh_viewer::opengl::Program::AttachShader (const Shader< shader_type > & shader) inline
Definition at line 19 of file program.h.
{
    glAttachShader(/*program=*/this->id_, /*shader=*/shader.id());
  }
References tiny_mesh_viewer::opengl::Shader< shader_type >::id(), and id_.
Referenced by tiny_mesh_viewer::shader::BlinnPhong::BlinnPhong().
GetUniformFloat()
float tiny_mesh_viewer::opengl::Program::GetUniformFloat (const std::string_view name) const
Definition at line 65 of file program.cc.
{
  float value;
  glGetUniformfv(/*program=*/this->id_,
                 glGetUniformLocation(/*program=*/this->id_, name.data()),
                 /*params=*/&value);
  return value;
}
References id_.
GetUniformMat4()
glm::mat4 tiny_mesh_viewer::opengl::Program::GetUniformMat4 (const std::string_view name) const
Definition at line 73 of file program.cc.
{
  glm::mat4 value;
  glGetUniformfv(/*program=*/this->id_,
                 glGetUniformLocation(/*program=*/this->id_, name.data()),
                 /*params=*/&value[0][0]);
  return value;
}
References id_.
GetUniformVec3()
glm::vec3 tiny_mesh_viewer::opengl::Program::GetUniformVec3 (const std::string_view name) const
Definition at line 81 of file program.cc.
{
  glm::vec3 value;
  glGetUniformfv(/*program=*/this->id_,
                 glGetUniformLocation(/*program=*/this->id_, name.data()),
                 /*params=*/&value[0]);
  return value;
}
References id_.
Link()
void tiny_mesh_viewer::opengl::Program::Link ()
Definition at line 21 of file program.cc.
                   {
  glLinkProgram(/*program=*/this->id_);
  int success;
  glGetProgramiv(/*program=*/this->id_, /*pname=*/GL_LINK_STATUS,
                 /*params=*/&success);
  if (!success) {
    static constexpr int kMaxLength = 1024;
    char info_log[kMaxLength];
    glGetProgramInfoLog(/*program=*/this->id_, kMaxLength, /*length=*/nullptr,
                        info_log);
    throw common::Exception<std::runtime_error>(
        /*loc=*/common::source_loc::current(),
        /*what=*/"glLinkProgram(): " + std::string(info_log));
  }
}
References id_.
Referenced by tiny_mesh_viewer::shader::BlinnPhong::BlinnPhong().
UniformFloat()
void tiny_mesh_viewer::opengl::Program::UniformFloat (const std::string_view name, const float value)
Definition at line 41 of file program.cc.
{
#ifdef DEBUG_UNIFORM
  dbg(name, value);
#endif
  glUniform1f(glGetUniformLocation(/*program=*/this->id_, name.data()),
              /*v0=*/value);
}
References id_.
Referenced by tiny_mesh_viewer::shader::BlinnPhong::LoadYAML().
UniformMat4()
void tiny_mesh_viewer::opengl::Program::UniformMat4 (const std::string_view name, const glm::mat4 & value)
Definition at line 49 of file program.cc.
{
#ifdef DEBUG_UNIFORM
  dbg(name, value);
#endif
  glUniformMatrix4fv(glGetUniformLocation(/*program=*/this->id_, name.data()),
                     /*count=*/1, /*transpose=*/GL_FALSE, &value[0][0]);
}
References id_.
Referenced by tiny_mesh_viewer::ui::Window::ConnectShader(), tiny_mesh_viewer::scene::Camera::ConnectShader(), and tiny_mesh_viewer::scene::Object::Draw().
UniformVec3()
void tiny_mesh_viewer::opengl::Program::UniformVec3 (const std::string_view name, const glm::vec3 & value)
Definition at line 57 of file program.cc.
{
#ifdef DEBUG_UNIFORM
  dbg(name, value);
#endif
  glUniform3fv(glGetUniformLocation(/*program=*/this->id_, name.data()),
               /*count=*/1, &value[0]);
}
References id_.
Referenced by tiny_mesh_viewer::scene::AmbientLight::ConnectShader(), tiny_mesh_viewer::scene::PointLight::ConnectShader(), tiny_mesh_viewer::scene::Camera::ConnectShader(), and tiny_mesh_viewer::scene::TriMesh::Draw().
Unuse()
void tiny_mesh_viewer::opengl::Program::Unuse ()
Definition at line 39 of file program.cc.
{ glUseProgram(/*program=*/0); }
Use()
void tiny_mesh_viewer::opengl::Program::Use ()
Definition at line 37 of file program.cc.
{ glUseProgram(/*program=*/this->id_); }
References id_.
Member Data Documentation
id_
GLuint tiny_mesh_viewer::opengl::Program::id_ private
Definition at line 35 of file program.h.
Referenced by AttachShader(), GetUniformFloat(), GetUniformMat4(), GetUniformVec3(), Link(), Program(), UniformFloat(), UniformMat4(), UniformVec3(), Use(), and ~Program().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/opengl/program.h
tiny_mesh_viewer/opengl/program.cc