tiny-mesh-viewer: tiny_mesh_viewer::common::Config Class Reference
tiny_mesh_viewer::common::Config Class Reference
#include <config.h>
Static Public Member Functions
static bool IsVec3 (const YAML::Node &yaml)
template<typename T = float, glm::qualifier Q = glm::defaultp>
static glm::tvec3< T, Q > AsTVec3 (const YAML::Node &yaml)
template<typename T = float, glm::qualifier Q = glm::defaultp>
static glm::tvec3< T, Q > AsTVec3 (const YAML::Node &yaml, const glm::tvec3< T, Q > &fallback)
static glm::vec3 AsVec3 (const YAML::Node &yaml)
static glm::vec3 AsVec3 (const YAML::Node &yaml, const glm::vec3 &fallback)
Detailed Description
Definition at line 9 of file config.h.
Member Function Documentation
AsTVec3() [1/2]
template<typename T = float, glm::qualifier Q = glm::defaultp> static glm::tvec3< T, Q > tiny_mesh_viewer::common::Config::AsTVec3 (const YAML::Node & yaml) inline static
Definition at line 14 of file config.h.
{
    return glm::tvec3<T, Q>(yaml[0].as<T>(), yaml[1].as<T>(), yaml[2].as<T>());
  }
AsTVec3() [2/2]
template<typename T = float, glm::qualifier Q = glm::defaultp> static glm::tvec3< T, Q > tiny_mesh_viewer::common::Config::AsTVec3 (const YAML::Node & yaml, const glm::tvec3< T, Q > & fallback) inline static
Definition at line 19 of file config.h.
{
    try {
      return glm::tvec3<T, Q>(yaml[0].as<T>(fallback[0]),
                              yaml[1].as<T>(fallback[1]),
                              yaml[2].as<T>(fallback[2]));
    } catch (...) {
      return fallback;
    }
  }
AsVec3() [1/2]
glm::vec3 tiny_mesh_viewer::common::Config::AsVec3 (const YAML::Node & yaml) static
Definition at line 18 of file config.cc.
{
  return Config::AsTVec3<glm::vec3::value_type>(yaml);
}
Referenced by tiny_mesh_viewer::scene::Camera::FromYAML(), tiny_mesh_viewer::scene::AmbientLight::FromYAML(), tiny_mesh_viewer::scene::PointLight::FromYAML(), tiny_mesh_viewer::scene::Object::FromYAML(), tiny_mesh_viewer::scene::TriMesh::FromYAML(), and tiny_mesh_viewer::ui::Canvas::FromYAML().
AsVec3() [2/2]
glm::vec3 tiny_mesh_viewer::common::Config::AsVec3 (const YAML::Node & yaml, const glm::vec3 & fallback) static
Definition at line 22 of file config.cc.
{
  return Config::AsTVec3<glm::vec3::value_type>(yaml, fallback);
}
IsVec3()
bool tiny_mesh_viewer::common::Config::IsVec3 (const YAML::Node & yaml) static
Definition at line 10 of file config.cc.
{
  return yaml.IsDefined() && yaml.IsSequence() && yaml.size() == 3 &&
         std::all_of(yaml.begin(), yaml.end(),
                     /*pred=*/[](const YAML::Node& node) -> bool {
                       return node.IsScalar();
                     });
}
The documentation for this class was generated from the following files:
tiny_mesh_viewer/common/config.h
tiny_mesh_viewer/common/config.cc