tiny-mesh-viewer: tiny_mesh_viewer::scene::Camera Class Reference
tiny_mesh_viewer::scene::Camera Class Reference
#include <camera.h>
Public Member Functions
Camera (const glm::vec3 &position=kDefaultPosition, const glm::vec3 &look_at=kDefaultLookAt, const glm::vec3 &up=kDefaultUp, const float fov=kDefaultFOV, const float z_near=kDefaultZNear, const float z_far=kDefaultZFar, const float translation_speed=kDefaultTranslationSpeed, const float yaw_speed=kDefaultYawSpeed, const float pitch_speed=kDefaultPitchSpeed)
void ConnectShader (shader::Shader &shader, ui::Window &window)
void ConnectPointLight (PointLight &point_light)
void TrackMovement (ui::Window &window, const float delta_time)
void TrackRotation (ui::Window &window, double x, double y)
glm::mat4 Projection (const float aspect) const
glm::vec3 position () const
void set_position (const glm::vec3 &position)
glm::vec3 look_at () const
void set_look_at (const glm::vec3 &look_at)
glm::vec3 up () const
void set_up (const glm::vec3 &up)
float fov () const
void set_fov (const float fov)
float z_near () const
void set_z_near (const float z_near)
float z_far () const
void set_z_far (const float z_far)
float translation_speed () const
void set_translation_speed (const float translation_speed)
float yaw_speed () const
void set_yaw_speed (const float yaw_speed)
float pitch_speed () const
void set_pitch_speed (const float pitch_speed)
Static Public Member Functions
static std::shared_ptr< Camera > FromYAML (const YAML::Node &yaml)
Public Attributes
boost::signals2::signal< void(const Camera &camera)> changed
Private Attributes
glm::vec3 look_at_
glm::vec3 position_
glm::vec3 up_
float fov_
float z_far_
float z_near_
float translation_speed_
float yaw_speed_
float pitch_speed_
glm::vec2 last_cursor_pos_
used for tracking mouse movement
Static Private Attributes
static constexpr glm::vec3 kDefaultPosition = glm::vec3(2.0, 0.0, 0.0)
static constexpr glm::vec3 kDefaultLookAt = glm::vec3(0.0, 0.0, 0.0)
static constexpr glm::vec3 kDefaultUp = glm::vec3(0.0, 1.0, 0.0)
static constexpr float kDefaultFOV = 45.0
static constexpr float kDefaultZNear = 0.1
static constexpr float kDefaultZFar = 100.0
static constexpr float kDefaultTranslationSpeed = 1.0
static constexpr float kDefaultYawSpeed = 1e-3
static constexpr float kDefaultPitchSpeed = 1e-3
Detailed Description
Definition at line 19 of file camera.h.
Constructor & Destructor Documentation
Camera()
tiny_mesh_viewer::scene::Camera::Camera (const glm::vec3 & position = kDefaultPosition, const glm::vec3 & look_at = kDefaultLookAt, const glm::vec3 & up = kDefaultUp, const float fov = kDefaultFOV, const float z_near = kDefaultZNear, const float z_far = kDefaultZFar, const float translation_speed = kDefaultTranslationSpeed, const float yaw_speed = kDefaultYawSpeed, const float pitch_speed = kDefaultPitchSpeed) explicit
Definition at line 20 of file camera.cc.
{
  this->set_position(position);
  this->set_look_at(look_at);
  this->set_up(up);
  this->set_fov(fov);
  this->set_z_near(z_near);
  this->set_z_far(z_far);
  this->set_translation_speed(translation_speed);
  this->set_yaw_speed(yaw_speed);
  this->set_pitch_speed(pitch_speed);
#ifdef DEBUG_CAMERA
  this->changed.connect([](const Camera& camera) -> void {
    INFO("Camera changed:");
    INFO("  position: {}", glm::to_string(camera.position()));
    INFO("  look_at: {}", glm::to_string(camera.look_at()));
    INFO("  up: {}", glm::to_string(camera.up()));
    INFO("  fov: {}", camera.fov());
    INFO("  z_near: {}", camera.z_near());
    INFO("  z_far: {}", camera.z_far());
    INFO("  translation_speed: {}", camera.translation_speed());
    INFO("  yaw_speed: {}", camera.yaw_speed());
    INFO("  pitch_speed: {}", camera.pitch_speed());
  });
#endif  // DEBUG_CAMERA
}
References changed, fov(), INFO, look_at(), pitch_speed(), position(), set_fov(), set_look_at(), set_pitch_speed(), set_position(), set_translation_speed(), set_up(), set_yaw_speed(), set_z_far(), set_z_near(), translation_speed(), up(), yaw_speed(), z_far(), and z_near().
Member Function Documentation
ConnectPointLight()
void tiny_mesh_viewer::scene::Camera::ConnectPointLight (PointLight & point_light)
Definition at line 62 of file camera.cc.
{
  this->changed.connect([&point_light](const Camera& camera) -> void {
    point_light.set_position(camera.position());
  });
}
References changed, position(), and tiny_mesh_viewer::scene::PointLight::set_position().
ConnectShader()
void tiny_mesh_viewer::scene::Camera::ConnectShader (shader::Shader & shader, ui::Window & window)
Definition at line 50 of file camera.cc.
{
  this->changed.connect([&shader, &window](const Camera& camera) -> void {
    auto with = common::WithUse(shader);
    glm::ivec2 size = window.FramebufferSize();
    float aspect = static_cast<float>(size.x) / static_cast<float>(size.y);
    auto&& projection = camera.Projection(aspect);
    shader.UniformMat4(/*name=*/"projection",
                       /*value=*/projection);
    shader.UniformVec3(/*name=*/"camera_position", /*value=*/camera.position());
  });
}
References changed, tiny_mesh_viewer::opengl::Window::FramebufferSize(), position(), Projection(), tiny_mesh_viewer::opengl::Program::UniformMat4(), and tiny_mesh_viewer::opengl::Program::UniformVec3().
Referenced by tiny_mesh_viewer::App::App().
fov()
float tiny_mesh_viewer::scene::Camera::fov () const
Definition at line 145 of file camera.cc.
{ return this->fov_; }
References fov_.
Referenced by Camera(), Projection(), and set_fov().
FromYAML()
std::shared_ptr< Camera > tiny_mesh_viewer::scene::Camera::FromYAML (const YAML::Node & yaml) static
Definition at line 184 of file camera.cc.
{
  if (!yaml.IsDefined()) return std::make_shared<Camera>();
  return std::make_shared<Camera>(
      /*position=*/common::Config::AsVec3(yaml["position"],
                                          /*fallback=*/kDefaultPosition),
      /*look_at=*/
      common::Config::AsVec3(yaml["look_at"], /*fallback=*/kDefaultLookAt),
      /*up=*/common::Config::AsVec3(yaml["up"], /*fallback=*/kDefaultUp),
      /*fov=*/yaml["fov"].as<float>(/*fallback=*/kDefaultFOV),
      /*z_near=*/yaml["z_near"].as<float>(/*fallback=*/kDefaultZNear),
      /*z_far=*/yaml["z_far"].as<float>(/*fallback=*/kDefaultZFar),
      /*translation_speed=*/
      yaml["translation_speed"].as<float>(
          /*fallback=*/kDefaultTranslationSpeed),
      /*yaw_speed=*/yaml["yaw_speed"].as<float>(/*fallback=*/kDefaultYawSpeed),
      /*pitch_speed=*/
      yaml["pitch_speed"].as<float>(/*fallback=*/kDefaultPitchSpeed));
}
References tiny_mesh_viewer::common::Config::AsVec3(), kDefaultFOV, kDefaultLookAt, kDefaultPitchSpeed, kDefaultPosition, kDefaultTranslationSpeed, kDefaultUp, kDefaultYawSpeed, kDefaultZFar, and kDefaultZNear.
Referenced by tiny_mesh_viewer::scene::Scene::FromYAML().
look_at()
glm::vec3 tiny_mesh_viewer::scene::Camera::look_at () const
Definition at line 131 of file camera.cc.
{ return this->look_at_; }
References look_at_.
Referenced by Camera(), Projection(), set_look_at(), TrackMovement(), and TrackRotation().
pitch_speed()
float tiny_mesh_viewer::scene::Camera::pitch_speed () const
Definition at line 178 of file camera.cc.
{ return this->pitch_speed_; }
References pitch_speed_.
Referenced by Camera(), and set_pitch_speed().
position()
glm::vec3 tiny_mesh_viewer::scene::Camera::position () const
Definition at line 124 of file camera.cc.
{ return this->position_; }
References position_.
Referenced by Camera(), ConnectPointLight(), ConnectShader(), Projection(), set_position(), TrackMovement(), and TrackRotation().
Projection()
glm::mat4 tiny_mesh_viewer::scene::Camera::Projection (const float aspect) const
Definition at line 118 of file camera.cc.
{
  return glm::perspective(/*fovy=*/glm::radians(/*degrees=*/this->fov()),
                          aspect, this->z_near(), this->z_far()) *
         glm::lookAt(this->position(), this->look_at(), this->up());
}
References fov(), look_at(), position(), up(), z_far(), and z_near().
Referenced by tiny_mesh_viewer::ui::Window::ConnectShader(), and ConnectShader().
set_fov()
void tiny_mesh_viewer::scene::Camera::set_fov (const float fov)
Definition at line 147 of file camera.cc.
{
  this->fov_ = fov;
  this->changed(*this);
}
References changed, fov(), and fov_.
Referenced by Camera().
set_look_at()
void tiny_mesh_viewer::scene::Camera::set_look_at (const glm::vec3 & look_at)
Definition at line 133 of file camera.cc.
{
  this->look_at_ = look_at;
  this->changed(*this);
}
References changed, look_at(), and look_at_.
Referenced by Camera(), TrackMovement(), and TrackRotation().
set_pitch_speed()
void tiny_mesh_viewer::scene::Camera::set_pitch_speed (const float pitch_speed)
Definition at line 180 of file camera.cc.
{
  this->pitch_speed_ = pitch_speed;
}
References pitch_speed(), and pitch_speed_.
Referenced by Camera().
set_position()
void tiny_mesh_viewer::scene::Camera::set_position (const glm::vec3 & position)
Definition at line 126 of file camera.cc.
{
  this->position_ = position;
  this->changed(*this);
}
References changed, position(), and position_.
Referenced by Camera(), and TrackMovement().
set_translation_speed()
void tiny_mesh_viewer::scene::Camera::set_translation_speed (const float translation_speed)
Definition at line 168 of file camera.cc.
{
  this->translation_speed_ = translation_speed;
}
References translation_speed(), and translation_speed_.
Referenced by Camera().
set_up()
void tiny_mesh_viewer::scene::Camera::set_up (const glm::vec3 & up)
Definition at line 140 of file camera.cc.
{
  this->up_ = up;
  this->changed(*this);
}
References changed, up(), and up_.
Referenced by Camera().
set_yaw_speed()
void tiny_mesh_viewer::scene::Camera::set_yaw_speed (const float yaw_speed)
Definition at line 174 of file camera.cc.
{
  this->yaw_speed_ = yaw_speed;
}
References yaw_speed(), and yaw_speed_.
Referenced by Camera().
set_z_far()
void tiny_mesh_viewer::scene::Camera::set_z_far (const float z_far)
Definition at line 161 of file camera.cc.
{
  this->z_far_ = z_far;
  this->changed(*this);
}
References changed, z_far(), and z_far_.
Referenced by Camera().
set_z_near()
void tiny_mesh_viewer::scene::Camera::set_z_near (const float z_near)
Definition at line 154 of file camera.cc.
{
  this->z_near_ = z_near;
  this->changed(*this);
}
References changed, z_near(), and z_near_.
Referenced by Camera().
TrackMovement()
void tiny_mesh_viewer::scene::Camera::TrackMovement (ui::Window & window, const float delta_time)
Definition at line 68 of file camera.cc.
{
  glm::vec3 front = glm::normalize(this->look_at() - this->position());
  glm::vec3 right = glm::normalize(glm::cross(front, this->up()));
  front = glm::normalize(glm::cross(this->up(), right));
  glm::vec3 position_change = glm::vec3(0.0);
  if (window.GetKey(GLFW_KEY_A) == GLFW_PRESS) {
    position_change -= this->translation_speed() * delta_time * right;
  }
  if (window.GetKey(GLFW_KEY_S) == GLFW_PRESS) {
    position_change -= this->translation_speed() * delta_time * front;
  }
  if (window.GetKey(GLFW_KEY_D) == GLFW_PRESS) {
    position_change += this->translation_speed() * delta_time * right;
  }
  if (window.GetKey(GLFW_KEY_W) == GLFW_PRESS) {
    position_change += this->translation_speed() * delta_time * front;
  }
  if (window.GetKey(GLFW_KEY_E) == GLFW_PRESS) {
    position_change += this->translation_speed() * delta_time * this->up();
  }
  if (window.GetKey(GLFW_KEY_Q) == GLFW_PRESS) {
    position_change -= this->translation_speed() * delta_time * this->up();
  }
  this->set_position(this->position() + position_change);
  this->set_look_at(this->look_at() + position_change);
}
References tiny_mesh_viewer::opengl::Window::GetKey(), look_at(), position(), set_look_at(), set_position(), translation_speed(), and up().
TrackRotation()
void tiny_mesh_viewer::scene::Camera::TrackRotation (ui::Window & window, double x, double y)
Definition at line 95 of file camera.cc.
{
  static constexpr float kEps = 1e-6;
  y = -y;
  if (glm::epsilonEqual(glm::length(this->last_cursor_pos_), 0.0f, kEps)) {
    this->last_cursor_pos_ = {x, y};
  }
  if (window.GetKey(GLFW_KEY_LEFT_ALT) == GLFW_PRESS ||
      window.GetKey(GLFW_KEY_RIGHT_ALT) == GLFW_PRESS) {
    auto&& front = glm::normalize(this->look_at() - this->position());
    auto&& euler = common::math::VectorToEuler(front);
    float yaw = euler[0];
    float pitch = euler[1];
    yaw -= this->yaw_speed_ * (x - this->last_cursor_pos_.x);
    pitch += this->pitch_speed_ * (y - this->last_cursor_pos_.y);
    pitch = glm::clamp(pitch, /*minVal=*/glm::radians(/*degrees=*/-89.0f),
                       /*maxVal=*/glm::radians(/*degrees=*/+89.0f));
    front = common::math::EulerToVector(glm::vec2(yaw, pitch));
    this->set_look_at(this->position() + front);
  }
  this->last_cursor_pos_ = {x, y};
}
References tiny_mesh_viewer::common::math::EulerToVector(), tiny_mesh_viewer::opengl::Window::GetKey(), last_cursor_pos_, look_at(), pitch_speed_, position(), set_look_at(), tiny_mesh_viewer::common::math::VectorToEuler(), and yaw_speed_.
translation_speed()
float tiny_mesh_viewer::scene::Camera::translation_speed () const
Definition at line 166 of file camera.cc.
{ return this->translation_speed_; }
References translation_speed_.
Referenced by Camera(), set_translation_speed(), and TrackMovement().
up()
glm::vec3 tiny_mesh_viewer::scene::Camera::up () const
Definition at line 138 of file camera.cc.
{ return this->up_; }
References up_.
Referenced by Camera(), Projection(), set_up(), and TrackMovement().
yaw_speed()
float tiny_mesh_viewer::scene::Camera::yaw_speed () const
Definition at line 172 of file camera.cc.
{ return this->yaw_speed_; }
References yaw_speed_.
Referenced by Camera(), and set_yaw_speed().
z_far()
float tiny_mesh_viewer::scene::Camera::z_far () const
Definition at line 159 of file camera.cc.
{ return this->z_far_; }
References z_far_.
Referenced by Camera(), Projection(), and set_z_far().
z_near()
float tiny_mesh_viewer::scene::Camera::z_near () const
Definition at line 152 of file camera.cc.
{ return this->z_near_; }
References z_near_.
Referenced by Camera(), Projection(), and set_z_near().
Member Data Documentation
changed
boost::signals2::signal<void(const Camera& camera)> tiny_mesh_viewer::scene::Camera::changed
Definition at line 59 of file camera.h.
Referenced by tiny_mesh_viewer::App::App(), Camera(), ConnectPointLight(), ConnectShader(), set_fov(), set_look_at(), set_position(), set_up(), set_z_far(), and set_z_near().
fov_
float tiny_mesh_viewer::scene::Camera::fov_ private
Definition at line 65 of file camera.h.
Referenced by fov(), and set_fov().
kDefaultFOV
constexpr float tiny_mesh_viewer::scene::Camera::kDefaultFOV = 45.0 static constexpr private
Definition at line 73 of file camera.h.
Referenced by FromYAML().
kDefaultLookAt
constexpr glm::vec3 tiny_mesh_viewer::scene::Camera::kDefaultLookAt = glm::vec3(0.0, 0.0, 0.0) static constexpr private
Definition at line 71 of file camera.h.
Referenced by FromYAML().
kDefaultPitchSpeed
constexpr float tiny_mesh_viewer::scene::Camera::kDefaultPitchSpeed = 1e-3 static constexpr private
Definition at line 78 of file camera.h.
Referenced by FromYAML().
kDefaultPosition
constexpr glm::vec3 tiny_mesh_viewer::scene::Camera::kDefaultPosition = glm::vec3(2.0, 0.0, 0.0) static constexpr private
Definition at line 70 of file camera.h.
Referenced by FromYAML().
kDefaultTranslationSpeed
constexpr float tiny_mesh_viewer::scene::Camera::kDefaultTranslationSpeed = 1.0 static constexpr private
Definition at line 76 of file camera.h.
Referenced by FromYAML().
kDefaultUp
constexpr glm::vec3 tiny_mesh_viewer::scene::Camera::kDefaultUp = glm::vec3(0.0, 1.0, 0.0) static constexpr private
Definition at line 72 of file camera.h.
Referenced by FromYAML().
kDefaultYawSpeed
constexpr float tiny_mesh_viewer::scene::Camera::kDefaultYawSpeed = 1e-3 static constexpr private
Definition at line 77 of file camera.h.
Referenced by FromYAML().
kDefaultZFar
constexpr float tiny_mesh_viewer::scene::Camera::kDefaultZFar = 100.0 static constexpr private
Definition at line 75 of file camera.h.
Referenced by FromYAML().
kDefaultZNear
constexpr float tiny_mesh_viewer::scene::Camera::kDefaultZNear = 0.1 static constexpr private
Definition at line 74 of file camera.h.
Referenced by FromYAML().
last_cursor_pos_
glm::vec2 tiny_mesh_viewer::scene::Camera::last_cursor_pos_ private
used for tracking mouse movement
Definition at line 68 of file camera.h.
Referenced by TrackRotation().
look_at_
glm::vec3 tiny_mesh_viewer::scene::Camera::look_at_ private
Definition at line 62 of file camera.h.
Referenced by look_at(), and set_look_at().
pitch_speed_
float tiny_mesh_viewer::scene::Camera::pitch_speed_ private
Definition at line 66 of file camera.h.
Referenced by pitch_speed(), set_pitch_speed(), and TrackRotation().
position_
glm::vec3 tiny_mesh_viewer::scene::Camera::position_ private
Definition at line 63 of file camera.h.
Referenced by position(), and set_position().
translation_speed_
float tiny_mesh_viewer::scene::Camera::translation_speed_ private
Definition at line 66 of file camera.h.
Referenced by set_translation_speed(), and translation_speed().
up_
glm::vec3 tiny_mesh_viewer::scene::Camera::up_ private
Definition at line 64 of file camera.h.
Referenced by set_up(), and up().
yaw_speed_
float tiny_mesh_viewer::scene::Camera::yaw_speed_ private
Definition at line 66 of file camera.h.
Referenced by set_yaw_speed(), TrackRotation(), and yaw_speed().
z_far_
float tiny_mesh_viewer::scene::Camera::z_far_ private
Definition at line 65 of file camera.h.
Referenced by set_z_far(), and z_far().
z_near_
float tiny_mesh_viewer::scene::Camera::z_near_ private
Definition at line 65 of file camera.h.
Referenced by set_z_near(), and z_near().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/scene/camera.h
tiny_mesh_viewer/scene/camera.cc