tiny-mesh-viewer: tiny_mesh_viewer::scene::AmbientLight Class Reference
tiny_mesh_viewer::scene::AmbientLight Class Reference
#include <ambient_light.h>
Public Member Functions
AmbientLight (const glm::vec3 &color=kDefaultColor)
void ConnectShader (shader::Shader &shader)
glm::vec3 color () const
void set_color (const glm::vec3 &color)
Static Public Member Functions
static std::shared_ptr< AmbientLight > FromYAML (const YAML::Node &yaml)
Public Attributes
boost::signals2::signal< void(const AmbientLight &ambient_light)> changed
Private Attributes
glm::vec3 color_
Static Private Attributes
static constexpr glm::vec3 kDefaultColor = glm::vec3(0.25, 0.25, 0.25)
Detailed Description
Definition at line 14 of file ambient_light.h.
Constructor & Destructor Documentation
AmbientLight()
tiny_mesh_viewer::scene::AmbientLight::AmbientLight (const glm::vec3 & color = kDefaultColor) explicit
Definition at line 15 of file ambient_light.cc.
{
  this->set_color(color);
#ifdef DEBUG_AMBIENT_LIGHT
  this->changed.connect([](const AmbientLight& ambient_light) -> void {
    INFO("AmbientLight changed:");
    INFO("  color: {}", glm::to_string(ambient_light.color()));
  });
#endif  // DEBUG_AMBIENT_LIGHT
}
References changed, color(), INFO, and set_color().
Member Function Documentation
color()
glm::vec3 tiny_mesh_viewer::scene::AmbientLight::color () const
Definition at line 33 of file ambient_light.cc.
{ return this->color_; }
References color_.
Referenced by AmbientLight(), ConnectShader(), and set_color().
ConnectShader()
void tiny_mesh_viewer::scene::AmbientLight::ConnectShader (shader::Shader & shader)
Definition at line 26 of file ambient_light.cc.
{
  this->changed.connect([&shader](const AmbientLight& ambient_light) -> void {
    auto with = common::WithUse(shader);
    shader.UniformVec3("ambient_light_color", ambient_light.color());
  });
}
References changed, color(), and tiny_mesh_viewer::opengl::Program::UniformVec3().
Referenced by tiny_mesh_viewer::App::App().
FromYAML()
std::shared_ptr< AmbientLight > tiny_mesh_viewer::scene::AmbientLight::FromYAML (const YAML::Node & yaml) static
Definition at line 40 of file ambient_light.cc.
{
  if (!yaml.IsDefined()) return std::make_shared<AmbientLight>();
  return std::make_shared<AmbientLight>(
      /*color=*/common::Config::AsVec3(yaml["color"],
                                       /*fallback=*/kDefaultColor));
}
References tiny_mesh_viewer::common::Config::AsVec3(), and kDefaultColor.
Referenced by tiny_mesh_viewer::scene::Scene::FromYAML().
set_color()
void tiny_mesh_viewer::scene::AmbientLight::set_color (const glm::vec3 & color)
Definition at line 35 of file ambient_light.cc.
{
  this->color_ = color;
  this->changed(*this);
}
References changed, color(), and color_.
Referenced by AmbientLight().
Member Data Documentation
changed
boost::signals2::signal<void(const AmbientLight& ambient_light)> tiny_mesh_viewer::scene::AmbientLight::changed
Definition at line 25 of file ambient_light.h.
Referenced by AmbientLight(), tiny_mesh_viewer::App::App(), ConnectShader(), and set_color().
color_
glm::vec3 tiny_mesh_viewer::scene::AmbientLight::color_ private
Definition at line 28 of file ambient_light.h.
Referenced by color(), and set_color().
kDefaultColor
constexpr glm::vec3 tiny_mesh_viewer::scene::AmbientLight::kDefaultColor = glm::vec3(0.25, 0.25, 0.25) static constexpr private
Definition at line 30 of file ambient_light.h.
Referenced by FromYAML().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/scene/light/ambient_light.h
tiny_mesh_viewer/scene/light/ambient_light.cc