tiny-mesh-viewer: tiny_mesh_viewer::scene::PointLight Class Reference
tiny_mesh_viewer::scene::PointLight Class Reference
#include <point_light.h>
Public Member Functions
PointLight (const glm::vec3 &position=kDefaultPosition, const glm::vec3 &color=kDefaultColor)
void ConnectShader (shader::Shader &shader)
glm::vec3 position () const
void set_position (const glm::vec3 &position)
glm::vec3 color () const
void set_color (const glm::vec3 &color)
Static Public Member Functions
static std::shared_ptr< PointLight > FromYAML (const YAML::Node &yaml)
Public Attributes
boost::signals2::signal< void(const PointLight &point_light)> changed
Private Attributes
glm::vec3 position_
glm::vec3 color_
Static Private Attributes
static constexpr glm::vec3 kDefaultPosition = glm::vec3(1.0, 1.0, -1.0)
static constexpr glm::vec3 kDefaultColor = glm::vec3(1.0, 1.0, 1.0)
Detailed Description
Definition at line 14 of file point_light.h.
Constructor & Destructor Documentation
PointLight()
tiny_mesh_viewer::scene::PointLight::PointLight (const glm::vec3 & position = kDefaultPosition, const glm::vec3 & color = kDefaultColor) explicit
Definition at line 13 of file point_light.cc.
{
  this->set_position(position);
  this->set_color(color);
#ifdef DEBUG_POINT_LIGHT
  this->changed.connect([](const PointLight& point_light) -> void {
    INFO("PointLight changed:");
    INFO("  position: {}", glm::to_string(point_light.position()));
    INFO("  color: {}", glm::to_string(point_light.color()));
  });
#endif  // DEBUG_POINT_LIGHT
}
References changed, color(), INFO, position(), set_color(), and set_position().
Member Function Documentation
color()
glm::vec3 tiny_mesh_viewer::scene::PointLight::color () const
Definition at line 43 of file point_light.cc.
{ return this->color_; }
References color_.
Referenced by ConnectShader(), PointLight(), and set_color().
ConnectShader()
void tiny_mesh_viewer::scene::PointLight::ConnectShader (shader::Shader & shader)
Definition at line 26 of file point_light.cc.
{
  this->changed.connect([&shader](const PointLight& point_light) -> void {
    auto with = common::WithUse(shader);
    shader.UniformVec3(/*name=*/"point_light_position",
                       /*value=*/point_light.position());
    shader.UniformVec3(/*name=*/"point_light_color",
                       /*value=*/point_light.color());
  });
}
References changed, color(), position(), and tiny_mesh_viewer::opengl::Program::UniformVec3().
Referenced by tiny_mesh_viewer::App::App().
FromYAML()
std::shared_ptr< PointLight > tiny_mesh_viewer::scene::PointLight::FromYAML (const YAML::Node & yaml) static
Definition at line 50 of file point_light.cc.
{
  if (!yaml.IsDefined()) return std::make_shared<PointLight>();
  return std::make_shared<PointLight>(
      /*position=*/common::Config::AsVec3(yaml["position"],
                                          /*fallback=*/kDefaultPosition),
      /*color=*/common::Config::AsVec3(yaml["color"],
                                       /*fallback=*/kDefaultColor));
}
References tiny_mesh_viewer::common::Config::AsVec3(), kDefaultColor, and kDefaultPosition.
Referenced by tiny_mesh_viewer::scene::Scene::FromYAML().
position()
glm::vec3 tiny_mesh_viewer::scene::PointLight::position () const
Definition at line 36 of file point_light.cc.
{ return this->position_; }
References position_.
Referenced by ConnectShader(), PointLight(), and set_position().
set_color()
void tiny_mesh_viewer::scene::PointLight::set_color (const glm::vec3 & color)
Definition at line 45 of file point_light.cc.
{
  this->color_ = color;
  this->changed(*this);
}
References changed, color(), and color_.
Referenced by PointLight().
set_position()
void tiny_mesh_viewer::scene::PointLight::set_position (const glm::vec3 & position)
Definition at line 38 of file point_light.cc.
{
  this->position_ = position;
  this->changed(*this);
}
References changed, position(), and position_.
Referenced by tiny_mesh_viewer::scene::Camera::ConnectPointLight(), and PointLight().
Member Data Documentation
changed
boost::signals2::signal<void(const PointLight& point_light)> tiny_mesh_viewer::scene::PointLight::changed
Definition at line 26 of file point_light.h.
Referenced by tiny_mesh_viewer::App::App(), ConnectShader(), PointLight(), set_color(), and set_position().
color_
glm::vec3 tiny_mesh_viewer::scene::PointLight::color_ private
Definition at line 32 of file point_light.h.
Referenced by color(), and set_color().
kDefaultColor
constexpr glm::vec3 tiny_mesh_viewer::scene::PointLight::kDefaultColor = glm::vec3(1.0, 1.0, 1.0) static constexpr private
Definition at line 35 of file point_light.h.
Referenced by FromYAML().
kDefaultPosition
constexpr glm::vec3 tiny_mesh_viewer::scene::PointLight::kDefaultPosition = glm::vec3(1.0, 1.0, -1.0) static constexpr private
Definition at line 34 of file point_light.h.
Referenced by FromYAML().
position_
glm::vec3 tiny_mesh_viewer::scene::PointLight::position_ private
Definition at line 31 of file point_light.h.
Referenced by position(), and set_position().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/scene/light/point_light.h
tiny_mesh_viewer/scene/light/point_light.cc