tiny-mesh-viewer: tiny_mesh_viewer::App Class Reference
tiny_mesh_viewer::App Class Reference
#include <app.h>
Public Member Functions
App (const YAML::Node &yaml={})
void Run ()
scene::Scene & scene ()
ui::Window & window ()
Public Member Functions inherited from tiny_mesh_viewer::opengl::App
App ()
~App ()
void Enable (GLenum cap)
void Init ()
void LoadGLLoader (GLADloadproc proc)
void Terminate ()
Private Attributes
std::shared_ptr< scene::Scene > scene_
std::map< std::string, std::shared_ptr< shader::Shader > > shaders_
std::unique_ptr< ui::Window > window_
Additional Inherited Members
Static Public Member Functions inherited from tiny_mesh_viewer::opengl::App
static double GetTime ()
static void PollEvents ()
Detailed Description
Definition at line 16 of file app.h.
Constructor & Destructor Documentation
App()
tiny_mesh_viewer::App::App (const YAML::Node & yaml = {}) explicit
Definition at line 22 of file app.cc.
{
  auto canvas = ui::Canvas::FromYAML(yaml["canvas"]);
  this->window_ = std::make_unique<ui::Window>(canvas);
  this->LoadGLLoader(reinterpret_cast<GLADloadproc>(glfwGetProcAddress));
  this->Enable(/*cap=*/GL_DEPTH_TEST);
  this->scene_ = scene::Scene::FromYAML(yaml["scene"]);
  this->window().canvas().set_scene(this->scene_);
  if (yaml["shaders"]) {
    std::for_each(yaml["shaders"].begin(), yaml["shaders"].end(),
                  [&shaders = this->shaders_, &scene = this->scene(),
                   &window = this->window()](const YAML::Node& yaml) -> void {
                    auto shader = shader::Shader::FromYAML(yaml);
                    scene.ambient_light().ConnectShader(*shader);
                    // scene.camera().ConnectPointLight(scene.point_light());
                    scene.camera().ConnectShader(*shader, window);
                    scene.point_light().ConnectShader(*shader);
                    window.ConnectShader(*shader, scene.camera());
                    shaders.insert({yaml["id"].as<std::string>(), shader});
                  });
  }
  std::for_each(
      this->scene().objects().begin(), this->scene().objects().end(),
      [&shaders =
           this->shaders_](std::shared_ptr<scene::Object> object) -> void {
        object->Load();
        object->set_shader(shaders.at(std::string(object->shader_id())));
      });
  this->window().cursor_moved.connect(
      [&camera = this->scene().camera()](ui::Window& window, double x,
                                         double y) -> void {
        camera.TrackRotation(window, x, y);
      });
  this->window().new_frame.connect(
      [&camera = this->scene().camera()](ui::Window& window,
                                         double delta_time) -> void {
        camera.TrackMovement(window, delta_time);
      });
  this->window().new_frame.connect([&objects = this->scene().objects()](
                                       ui::Window& window,
                                       double delta_time) -> void {
    std::for_each(objects.begin(), objects.end(),
                  [&delta_time](std::shared_ptr<scene::Object> object) -> void {
                    object->Update(delta_time);
                  });
  });
  this->scene().camera().changed(this->scene().camera());
  this->scene().ambient_light().changed(this->scene().ambient_light());
  this->scene().point_light().changed(this->scene().point_light());
}
References tiny_mesh_viewer::scene::Scene::ambient_light(), tiny_mesh_viewer::scene::Scene::camera(), tiny_mesh_viewer::ui::Window::canvas(), tiny_mesh_viewer::scene::Camera::changed, tiny_mesh_viewer::scene::AmbientLight::changed, tiny_mesh_viewer::scene::PointLight::changed, tiny_mesh_viewer::scene::AmbientLight::ConnectShader(), tiny_mesh_viewer::scene::PointLight::ConnectShader(), tiny_mesh_viewer::ui::Window::ConnectShader(), tiny_mesh_viewer::scene::Camera::ConnectShader(), tiny_mesh_viewer::ui::Window::cursor_moved, tiny_mesh_viewer::opengl::App::Enable(), tiny_mesh_viewer::scene::Scene::FromYAML(), tiny_mesh_viewer::shader::Shader::FromYAML(), tiny_mesh_viewer::ui::Canvas::FromYAML(), tiny_mesh_viewer::opengl::App::LoadGLLoader(), tiny_mesh_viewer::ui::Window::new_frame, tiny_mesh_viewer::scene::Scene::point_light(), scene(), scene_, tiny_mesh_viewer::ui::Canvas::set_scene(), shaders_, window(), and window_.
Member Function Documentation
Run()
void tiny_mesh_viewer::App::Run ()
Definition at line 79 of file app.cc.
{ this->window().Run(); }
References tiny_mesh_viewer::ui::Window::Run(), and window().
scene()
scene::Scene & tiny_mesh_viewer::App::scene ()
Definition at line 81 of file app.cc.
{ return *(this->scene_); }
References scene_.
Referenced by App().
window()
ui::Window & tiny_mesh_viewer::App::window ()
Definition at line 83 of file app.cc.
{ return *(this->window_); }
References window_.
Referenced by App(), and Run().
Member Data Documentation
scene_
std::shared_ptr<scene::Scene> tiny_mesh_viewer::App::scene_ private
Definition at line 26 of file app.h.
Referenced by App(), and scene().
shaders_
std::map<std::string, std::shared_ptr<shader::Shader> > tiny_mesh_viewer::App::shaders_ private
Definition at line 27 of file app.h.
Referenced by App().
window_
std::unique_ptr<ui::Window> tiny_mesh_viewer::App::window_ private
Definition at line 28 of file app.h.
Referenced by App(), and window().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/app.h
tiny_mesh_viewer/app.cc