tiny-mesh-viewer: tiny_mesh_viewer::shader::BlinnPhong Class Reference
tiny_mesh_viewer::shader::BlinnPhong Class Reference
#include <blinn_phong.h>
Public Member Functions
BlinnPhong (const std::filesystem::path &vertex_shader_filepath, const std::filesystem::path &fragment_shader_filepath)
virtual ~BlinnPhong ()=default
void LoadYAML (const YAML::Node &yaml)
Load additional parameters from YAML.
Public Member Functions inherited from tiny_mesh_viewer::shader::Shader
Shader ()=default
virtual ~Shader ()=default
Public Member Functions inherited from tiny_mesh_viewer::opengl::Program
Program ()
~Program ()
template<GLenum shader_type>
void AttachShader (const Shader< shader_type > &shader)
void Link ()
void Use ()
void Unuse ()
void UniformFloat (const std::string_view name, const float value)
void UniformMat4 (const std::string_view name, const glm::mat4 &value)
void UniformVec3 (const std::string_view name, const glm::vec3 &value)
float GetUniformFloat (const std::string_view name) const
glm::mat4 GetUniformMat4 (const std::string_view name) const
glm::vec3 GetUniformVec3 (const std::string_view name) const
Static Private Attributes
static constexpr float kDefaultAmbientReflection = 1.0
static constexpr float kDefaultDiffuseReflection = 1.0
static constexpr float kDefaultSpecularReflection = 1.0
static constexpr float kDefaultShininess = 80.0
Additional Inherited Members
Static Public Member Functions inherited from tiny_mesh_viewer::shader::Shader
static std::shared_ptr< Shader > FromYAML (const YAML::Node &yaml)
Detailed Description
Definition at line 12 of file blinn_phong.h.
Constructor & Destructor Documentation
BlinnPhong()
tiny_mesh_viewer::shader::BlinnPhong::BlinnPhong (const std::filesystem::path & vertex_shader_filepath, const std::filesystem::path & fragment_shader_filepath) explicit
Definition at line 11 of file blinn_phong.cc.
{
  auto vertex_shader = std::make_unique<opengl::VertexShader>();
  {
    cmrc::file file = common::Resource::Open(vertex_shader_filepath);
    const char* source = file.begin();
    vertex_shader->Source(/*count=*/1, /*string=*/&source);
    vertex_shader->Compile();
  }
  auto fragment_shader = std::make_unique<opengl::FragmentShader>();
  {
    cmrc::file file = common::Resource::Open(fragment_shader_filepath);
    const char* source = file.begin();
    fragment_shader->Source(/*count=*/1, /*string=*/&source);
    fragment_shader->Compile();
  }
  this->AttachShader(*vertex_shader);
  this->AttachShader(*fragment_shader);
  this->Link();
}
References tiny_mesh_viewer::opengl::Program::AttachShader(), tiny_mesh_viewer::opengl::Program::Link(), and tiny_mesh_viewer::common::Resource::Open().
~BlinnPhong()
virtual tiny_mesh_viewer::shader::BlinnPhong::~BlinnPhong () virtual default
Member Function Documentation
LoadYAML()
void tiny_mesh_viewer::shader::BlinnPhong::LoadYAML (const YAML::Node & yaml)
Load additional parameters from YAML.
Definition at line 32 of file blinn_phong.cc.
{
  this->UniformFloat(
      /*name=*/"ambient_reflection",
      /*value=*/yaml["ambient_reflection"].as<float>(
          /*fallback=*/kDefaultAmbientReflection));
  this->UniformFloat(
      /*name=*/"diffuse_reflection",
      /*value=*/yaml["diffuse_reflection"].as<float>(
          /*fallback=*/kDefaultDiffuseReflection));
  this->UniformFloat(
      /*name=*/"specular_reflection",
      /*value=*/yaml["specular_reflection"].as<float>(
          /*fallback=*/kDefaultSpecularReflection));
  this->UniformFloat(
      /*name=*/"shininess",
      /*value=*/yaml["shininess"].as<float>(/*fallback=*/kDefaultShininess));
}
References kDefaultAmbientReflection, kDefaultDiffuseReflection, kDefaultShininess, kDefaultSpecularReflection, and tiny_mesh_viewer::opengl::Program::UniformFloat().
Member Data Documentation
kDefaultAmbientReflection
constexpr float tiny_mesh_viewer::shader::BlinnPhong::kDefaultAmbientReflection = 1.0 static constexpr private
Definition at line 23 of file blinn_phong.h.
Referenced by LoadYAML().
kDefaultDiffuseReflection
constexpr float tiny_mesh_viewer::shader::BlinnPhong::kDefaultDiffuseReflection = 1.0 static constexpr private
Definition at line 24 of file blinn_phong.h.
Referenced by LoadYAML().
kDefaultShininess
constexpr float tiny_mesh_viewer::shader::BlinnPhong::kDefaultShininess = 80.0 static constexpr private
Definition at line 26 of file blinn_phong.h.
Referenced by LoadYAML().
kDefaultSpecularReflection
constexpr float tiny_mesh_viewer::shader::BlinnPhong::kDefaultSpecularReflection = 1.0 static constexpr private
Definition at line 25 of file blinn_phong.h.
Referenced by LoadYAML().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/shader/blinn_phong.h
tiny_mesh_viewer/shader/blinn_phong.cc