tiny-mesh-viewer: tiny_mesh_viewer::scene::Object Class Reference
tiny_mesh_viewer::scene::Object Class Reference
#include <object.h>
Public Member Functions
Object (const glm::vec3 &position=kDefaultPosition, const glm::vec3 &rotation=kDefaultRotation, const glm::vec3 &translation_speed=kDefaultTranslationSpeed, const glm::vec3 &rotation_speed=kDefaultRotationSpeed)
virtual ~Object ()=default
virtual void Draw ()
virtual void Load ()
Create OpenGL object and copy data to buffers.
void Update (const float delta_time)
Update position & rotation.
glm::mat4 ModelView () const
glm::mat4 NormalMatrix () const
glm::vec3 position () const
void set_position (const glm::vec3 &position)
glm::vec3 rotation () const
void set_rotation (const glm::vec3 &rotation)
glm::vec3 translation_speed () const
void set_translation_speed (const glm::vec3 &translation_speed)
glm::vec3 rotation_speed () const
void set_rotation_speed (const glm::vec3 &rotation_speed)
shader::Shader & shader ()
void set_shader (std::shared_ptr< shader::Shader > shader)
std::string_view shader_id () const
void set_shader_id (const std::string_view shader_id)
Static Public Member Functions
static std::shared_ptr< Object > FromYAML (const YAML::Node &yaml)
Protected Attributes
glm::vec3 position_
glm::vec3 rotation_
glm::vec3 translation_speed_
glm::vec3 rotation_speed_
std::shared_ptr< shader::Shader > shader_
std::string shader_id_
Static Protected Attributes
static constexpr glm::vec3 kDefaultPosition = glm::vec3(0.0, 0.0, 0.0)
static constexpr glm::vec3 kDefaultRotation = glm::vec3(0.0, 0.0, 0.0)
static constexpr glm::vec3 kDefaultTranslationSpeed
static constexpr glm::vec3 kDefaultRotationSpeed = glm::vec3(0.0, 0.0, 0.0)
Detailed Description
Definition at line 14 of file object.h.
Constructor & Destructor Documentation
Object()
tiny_mesh_viewer::scene::Object::Object (const glm::vec3 & position = kDefaultPosition, const glm::vec3 & rotation = kDefaultRotation, const glm::vec3 & translation_speed = kDefaultTranslationSpeed, const glm::vec3 & rotation_speed = kDefaultRotationSpeed)
Definition at line 20 of file object.cc.
{
  this->set_position(position);
  this->set_rotation(rotation);
  this->set_translation_speed(translation_speed);
  this->set_rotation_speed(rotation_speed);
}
References set_position(), set_rotation(), set_rotation_speed(), and set_translation_speed().
~Object()
virtual tiny_mesh_viewer::scene::Object::~Object () virtual default
Member Function Documentation
Draw()
void tiny_mesh_viewer::scene::Object::Draw () virtual
Reimplemented in tiny_mesh_viewer::scene::TriMesh.
Definition at line 29 of file object.cc.
                  {
  if (!this->shader_) return;
  auto with = common::WithUse(this->shader());
  this->shader().UniformMat4(
      /*name=*/"model_view",
      /*value=*/this->ModelView());
  this->shader().UniformMat4(/*name=*/"normal_matrix",
                             /*value=*/this->NormalMatrix());
}
References ModelView(), NormalMatrix(), shader(), shader_, and tiny_mesh_viewer::opengl::Program::UniformMat4().
Referenced by tiny_mesh_viewer::scene::TriMesh::Draw().
FromYAML()
std::shared_ptr< Object > tiny_mesh_viewer::scene::Object::FromYAML (const YAML::Node & yaml) static
Definition at line 95 of file object.cc.
{
  auto&& type = yaml["type"].as<std::string>();
  std::shared_ptr<Object> object = nullptr;
  if (type == "TriMesh") {
    object = TriMesh::FromYAML(yaml);
  } else {
    throw common::Exception<std::runtime_error>(
        /*loc=*/common::source_loc::current(),
        /*what=*/"Unknown object type: " + type);
  }
  object->set_shader_id(yaml["shader_id"].as<std::string>());
  object->set_position(
      common::Config::AsVec3(yaml["position"], /*fallback=*/kDefaultPosition));
  object->set_rotation(
      common::Config::AsVec3(yaml["rotation"], /*fallback=*/kDefaultRotation));
  object->set_translation_speed(
      common::Config::AsVec3(yaml["translation_speed"],
                             /*fallback=*/kDefaultTranslationSpeed));
  object->set_rotation_speed(
      common::Config::AsVec3(yaml["rotation_speed"],
                             /*fallback=*/kDefaultRotationSpeed));
  return object;
}
References tiny_mesh_viewer::common::Config::AsVec3(), tiny_mesh_viewer::scene::TriMesh::FromYAML(), kDefaultPosition, kDefaultRotation, kDefaultRotationSpeed, and kDefaultTranslationSpeed.
Referenced by tiny_mesh_viewer::scene::Scene::FromYAML().
Load()
void tiny_mesh_viewer::scene::Object::Load () virtual
Create OpenGL object and copy data to buffers.
Reimplemented in tiny_mesh_viewer::scene::TriMesh.
Definition at line 39 of file object.cc.
{}
ModelView()
glm::mat4 tiny_mesh_viewer::scene::Object::ModelView () const
Definition at line 46 of file object.cc.
{
  glm::mat4 model_view =
      glm::translate(glm::identity<glm::mat4>(), this->position());
  auto&& rotation = glm::radians(this->rotation());
  model_view =
      model_view * glm::eulerAngleXYZ(rotation.x, rotation.y, rotation.z);
  return model_view;
}
References position(), and rotation().
Referenced by Draw(), and NormalMatrix().
NormalMatrix()
glm::mat4 tiny_mesh_viewer::scene::Object::NormalMatrix () const
Definition at line 55 of file object.cc.
{
  return glm::inverseTranspose(this->ModelView());
}
References ModelView().
Referenced by Draw().
position()
glm::vec3 tiny_mesh_viewer::scene::Object::position () const
Definition at line 59 of file object.cc.
{ return this->position_; }
References position_.
Referenced by tiny_mesh_viewer::scene::TriMesh::Load(), ModelView(), set_position(), and Update().
rotation()
glm::vec3 tiny_mesh_viewer::scene::Object::rotation () const
Definition at line 65 of file object.cc.
{ return this->rotation_; }
References rotation_.
Referenced by ModelView(), set_rotation(), and Update().
rotation_speed()
glm::vec3 tiny_mesh_viewer::scene::Object::rotation_speed () const
Definition at line 77 of file object.cc.
{ return this->rotation_speed_; }
References rotation_speed_.
Referenced by set_rotation_speed(), and Update().
set_position()
void tiny_mesh_viewer::scene::Object::set_position (const glm::vec3 & position)
Definition at line 61 of file object.cc.
{
  this->position_ = position;
}
References position(), and position_.
Referenced by Object(), and Update().
set_rotation()
void tiny_mesh_viewer::scene::Object::set_rotation (const glm::vec3 & rotation)
Definition at line 67 of file object.cc.
{
  this->rotation_ = rotation;
}
References rotation(), and rotation_.
Referenced by Object(), and Update().
set_rotation_speed()
void tiny_mesh_viewer::scene::Object::set_rotation_speed (const glm::vec3 & rotation_speed)
Definition at line 79 of file object.cc.
{
  this->rotation_speed_ = rotation_speed;
}
References rotation_speed(), and rotation_speed_.
Referenced by Object().
set_shader()
void tiny_mesh_viewer::scene::Object::set_shader (std::shared_ptr< shader::Shader > shader)
Definition at line 85 of file object.cc.
{
  this->shader_ = shader;
}
References shader(), and shader_.
set_shader_id()
void tiny_mesh_viewer::scene::Object::set_shader_id (const std::string_view shader_id)
Definition at line 91 of file object.cc.
{
  this->shader_id_ = shader_id;
}
References shader_id(), and shader_id_.
set_translation_speed()
void tiny_mesh_viewer::scene::Object::set_translation_speed (const glm::vec3 & translation_speed)
Definition at line 73 of file object.cc.
{
  this->translation_speed_ = translation_speed;
}
References translation_speed(), and translation_speed_.
Referenced by Object().
shader()
shader::Shader & tiny_mesh_viewer::scene::Object::shader ()
Definition at line 83 of file object.cc.
{ return *(this->shader_); }
References shader_.
Referenced by Draw(), tiny_mesh_viewer::scene::TriMesh::Draw(), and set_shader().
shader_id()
std::string_view tiny_mesh_viewer::scene::Object::shader_id () const
Definition at line 89 of file object.cc.
{ return this->shader_id_; }
References shader_id_.
Referenced by set_shader_id().
translation_speed()
glm::vec3 tiny_mesh_viewer::scene::Object::translation_speed () const
Definition at line 71 of file object.cc.
{ return this->translation_speed_; }
References translation_speed_.
Referenced by set_translation_speed(), and Update().
Update()
void tiny_mesh_viewer::scene::Object::Update (const float delta_time)
Update position & rotation.
Definition at line 41 of file object.cc.
{
  this->set_position(this->position() + this->translation_speed() * delta_time);
  this->set_rotation(this->rotation() + this->rotation_speed() * delta_time);
}
References position(), rotation(), rotation_speed(), set_position(), set_rotation(), and translation_speed().
Member Data Documentation
kDefaultPosition
constexpr glm::vec3 tiny_mesh_viewer::scene::Object::kDefaultPosition = glm::vec3(0.0, 0.0, 0.0) static constexpr protected
Definition at line 59 of file object.h.
Referenced by FromYAML().
kDefaultRotation
constexpr glm::vec3 tiny_mesh_viewer::scene::Object::kDefaultRotation = glm::vec3(0.0, 0.0, 0.0) static constexpr protected
Definition at line 60 of file object.h.
Referenced by FromYAML().
kDefaultRotationSpeed
constexpr glm::vec3 tiny_mesh_viewer::scene::Object::kDefaultRotationSpeed = glm::vec3(0.0, 0.0, 0.0) static constexpr protected
Definition at line 63 of file object.h.
Referenced by FromYAML().
kDefaultTranslationSpeed
constexpr glm::vec3 tiny_mesh_viewer::scene::Object::kDefaultTranslationSpeed static constexpr protected
Initial value:
=
      glm::vec3(0.0, 0.0, 0.0)
Definition at line 61 of file object.h.
Referenced by FromYAML().
position_
glm::vec3 tiny_mesh_viewer::scene::Object::position_ protected
Definition at line 51 of file object.h.
Referenced by position(), and set_position().
rotation_
glm::vec3 tiny_mesh_viewer::scene::Object::rotation_ protected
Definition at line 52 of file object.h.
Referenced by rotation(), and set_rotation().
rotation_speed_
glm::vec3 tiny_mesh_viewer::scene::Object::rotation_speed_ protected
Definition at line 54 of file object.h.
Referenced by rotation_speed(), and set_rotation_speed().
shader_
std::shared_ptr<shader::Shader> tiny_mesh_viewer::scene::Object::shader_ protected
Definition at line 56 of file object.h.
Referenced by Draw(), tiny_mesh_viewer::scene::TriMesh::Draw(), set_shader(), and shader().
shader_id_
std::string tiny_mesh_viewer::scene::Object::shader_id_ protected
Definition at line 57 of file object.h.
Referenced by set_shader_id(), and shader_id().
translation_speed_
glm::vec3 tiny_mesh_viewer::scene::Object::translation_speed_ protected
Definition at line 53 of file object.h.
Referenced by set_translation_speed(), and translation_speed().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/scene/object/object.h
tiny_mesh_viewer/scene/object/object.cc