tiny-mesh-viewer: tiny_mesh_viewer::ui::Window Class Reference
tiny_mesh_viewer::ui::Window Class Reference
#include <window.h>
Public Member Functions
Window (const int width=800, const int height=600, const std::string_view title="Tiny Mesh Viewer", GLFWmonitor *monitor=nullptr, GLFWwindow *share=nullptr)
Window (std::shared_ptr< Canvas > canvas)
void Run ()
void ConnectShader (shader::Shader &shader, scene::Camera &camera)
Canvas & canvas ()
Public Member Functions inherited from tiny_mesh_viewer::opengl::Window
Window (const int width=800, const int height=600, const std::string_view title="Tiny Mesh Viewer", GLFWmonitor *monitor=nullptr, GLFWwindow *share=nullptr)
~Window ()
glm::ivec2 FramebufferSize () const
int GetKey (int key)
void MakeContextCurrent ()
GLFWcursorposfun SetCursorPosCallback (GLFWcursorposfun callback)
GLFWframebuffersizefun SetFramebufferSizeCallback (GLFWframebuffersizefun callback)
void SetTitle (const std::string_view title)
void SetWindowUserPointer (void *pointer)
int ShouldClose ()
void SwapBuffers ()
Public Attributes
boost::signals2::signal< void(Window &window, int width, int height)> framebuffer_size_changed
boost::signals2::signal< void(Window &window, double frame_duration)> new_frame
boost::signals2::signal< void(Window &window, double x, double y)> cursor_moved
Protected Member Functions
void Init ()
Private Attributes
std::shared_ptr< Canvas > canvas_
double last_frame_time_ = 0.0
used to compute FPS
Additional Inherited Members
Static Public Member Functions inherited from tiny_mesh_viewer::opengl::Window
static void Hint (const int hint, const int value)
Detailed Description
Definition at line 18 of file window.h.
Constructor & Destructor Documentation
Window() [1/2]
tiny_mesh_viewer::ui::Window::Window (const int width = 800, const int height = 600, const std::string_view title = "Tiny Mesh Viewer", GLFWmonitor * monitor = nullptr, GLFWwindow * share = nullptr) explicit
Definition at line 24 of file window.cc.
    : tiny_mesh_viewer::opengl::Window(width, height, title, monitor, share) {
  this->canvas_ = std::make_shared<Canvas>();
  this->Init();
}
References canvas_, and Init().
Window() [2/2]
tiny_mesh_viewer::ui::Window::Window (std::shared_ptr< Canvas > canvas) explicit
Definition at line 19 of file window.cc.
{
  this->canvas_ = canvas;
  this->Init();
}
References canvas(), canvas_, and Init().
Member Function Documentation
canvas()
Canvas & tiny_mesh_viewer::ui::Window::canvas ()
Definition at line 53 of file window.cc.
{ return *(this->canvas_); }
References canvas_.
Referenced by tiny_mesh_viewer::App::App(), Run(), and Window().
ConnectShader()
void tiny_mesh_viewer::ui::Window::ConnectShader (shader::Shader & shader, scene::Camera & camera)
Definition at line 43 of file window.cc.
{
  this->framebuffer_size_changed.connect(
      [&shader, &camera](Window& window, int width, int height) -> void {
        auto with = common::WithUse(shader);
        auto aspect = static_cast<float>(width) / static_cast<float>(height);
        shader.UniformMat4(/*name*/ "projection",
                           /*value=*/camera.Projection(aspect));
      });
}
References framebuffer_size_changed, tiny_mesh_viewer::scene::Camera::Projection(), and tiny_mesh_viewer::opengl::Program::UniformMat4().
Referenced by tiny_mesh_viewer::App::App().
Init()
void tiny_mesh_viewer::ui::Window::Init () protected
Definition at line 55 of file window.cc.
                  {
  this->MakeContextCurrent();
  this->SetWindowUserPointer(this);
  this->SetCursorPosCallback(
      [](GLFWwindow* window, double x, double y) -> void {
        auto* self = static_cast<Window*>(glfwGetWindowUserPointer(window));
        self->cursor_moved(*self, x, y);
      });
  this->SetFramebufferSizeCallback(
      [](GLFWwindow* window, int width, int height) -> void {
        auto* self = static_cast<Window*>(glfwGetWindowUserPointer(window));
        glViewport(/*x=*/0, /*y=*/0, width, height);
        self->framebuffer_size_changed(*self, width, height);
      });
  this->new_frame.connect([](Window& window, double frame_duration) -> void {
    static int frames = 0;
    static float duration = 0.0;
    ++frames;
    duration += frame_duration;
    if (duration > 1.0) {
      window.SetTitle(
          fmt::format(/*fmt=*/"Tiny Mesh Viewer ({} FPS)", frames / duration));
      duration = 0.0;
      frames = 0;
    }
  });
#ifdef DEBUG_WINDOW
  this->framebuffer_size_changed.connect(
      [](Window& window, int width, int height) -> void {
        INFO("Framebuffer size changed: {}x{}", width, height);
      });
#endif  // DEBUG_WINDOW
}
References cursor_moved, framebuffer_size_changed, INFO, tiny_mesh_viewer::opengl::Window::MakeContextCurrent(), new_frame, tiny_mesh_viewer::opengl::Window::SetCursorPosCallback(), tiny_mesh_viewer::opengl::Window::SetFramebufferSizeCallback(), and tiny_mesh_viewer::opengl::Window::SetWindowUserPointer().
Referenced by Window().
Run()
void tiny_mesh_viewer::ui::Window::Run ()
Definition at line 31 of file window.cc.
                 {
  while (!this->ShouldClose()) {
    double current_time = opengl::App::GetTime();
    double delta_time = current_time - this->last_frame_time_;
    this->last_frame_time_ = current_time;
    this->new_frame(*this, delta_time);
    this->canvas().Draw();
    this->SwapBuffers();
    opengl::App::PollEvents();
  }
}
References canvas(), tiny_mesh_viewer::ui::Canvas::Draw(), tiny_mesh_viewer::opengl::App::GetTime(), last_frame_time_, new_frame, tiny_mesh_viewer::opengl::App::PollEvents(), tiny_mesh_viewer::opengl::Window::ShouldClose(), and tiny_mesh_viewer::opengl::Window::SwapBuffers().
Referenced by tiny_mesh_viewer::App::Run().
Member Data Documentation
canvas_
std::shared_ptr<Canvas> tiny_mesh_viewer::ui::Window::canvas_ private
Definition at line 42 of file window.h.
Referenced by canvas(), and Window().
cursor_moved
boost::signals2::signal<void(Window& window, double x, double y)> tiny_mesh_viewer::ui::Window::cursor_moved
Definition at line 36 of file window.h.
Referenced by tiny_mesh_viewer::App::App(), and Init().
framebuffer_size_changed
boost::signals2::signal<void(Window& window, int width, int height)> tiny_mesh_viewer::ui::Window::framebuffer_size_changed
Definition at line 32 of file window.h.
Referenced by ConnectShader(), and Init().
last_frame_time_
double tiny_mesh_viewer::ui::Window::last_frame_time_ = 0.0 private
used to compute FPS
Definition at line 44 of file window.h.
Referenced by Run().
new_frame
boost::signals2::signal<void(Window& window, double frame_duration)> tiny_mesh_viewer::ui::Window::new_frame
Definition at line 34 of file window.h.
Referenced by tiny_mesh_viewer::App::App(), Init(), and Run().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/ui/window.h
tiny_mesh_viewer/ui/window.cc