tiny-mesh-viewer: tiny_mesh_viewer::ui::Canvas Class Reference
tiny_mesh_viewer::ui::Canvas Class Reference
#include <canvas.h>
Public Member Functions
Canvas (const glm::vec3 &color=kDefaultColor)
void Draw ()
void Clear (GLbitfield mask=GL_DEPTH_BUFFER_BIT|GL_COLOR_BUFFER_BIT)
void ClearColor ()
scene::Scene & scene ()
void set_scene (std::shared_ptr< scene::Scene > scene)
Static Public Member Functions
static std::shared_ptr< Canvas > FromYAML (const YAML::Node &yaml)
Private Attributes
std::shared_ptr< scene::Scene > scene_
glm::vec3 color_
Static Private Attributes
static constexpr glm::vec3 kDefaultColor
Detailed Description
Definition at line 14 of file canvas.h.
Constructor & Destructor Documentation
Canvas()
tiny_mesh_viewer::ui::Canvas::Canvas (const glm::vec3 & color = kDefaultColor)
Definition at line 9 of file canvas.cc.
: color_(color) {}
Member Function Documentation
Clear()
void tiny_mesh_viewer::ui::Canvas::Clear (GLbitfield mask = GL_DEPTH_BUFFER_BIT | GL_COLOR_BUFFER_BIT)
Definition at line 20 of file canvas.cc.
{ glClear(mask); }
Referenced by Draw().
ClearColor()
void tiny_mesh_viewer::ui::Canvas::ClearColor ()
Definition at line 22 of file canvas.cc.
{
  glClearColor(this->color_.r, this->color_.g, this->color_.b, /*alpha=*/1.0);
}
References color_.
Referenced by Draw().
Draw()
void tiny_mesh_viewer::ui::Canvas::Draw ()
Definition at line 11 of file canvas.cc.
                  {
  this->ClearColor();
  this->Clear();
  if (this->scene_) {
    this->scene().Draw();
  }
}
References Clear(), ClearColor(), tiny_mesh_viewer::scene::Scene::Draw(), scene(), and scene_.
Referenced by tiny_mesh_viewer::ui::Window::Run().
FromYAML()
std::shared_ptr< Canvas > tiny_mesh_viewer::ui::Canvas::FromYAML (const YAML::Node & yaml) static
Definition at line 32 of file canvas.cc.
{
  if (!yaml.IsDefined()) return std::make_shared<Canvas>();
  return std::make_shared<Canvas>(
      common::Config::AsVec3(yaml["color"], /*fallback=*/kDefaultColor));
}
References tiny_mesh_viewer::common::Config::AsVec3(), and kDefaultColor.
Referenced by tiny_mesh_viewer::App::App().
scene()
scene::Scene & tiny_mesh_viewer::ui::Canvas::scene ()
Definition at line 26 of file canvas.cc.
{ return *(this->scene_); }
References scene_.
Referenced by Draw(), and set_scene().
set_scene()
void tiny_mesh_viewer::ui::Canvas::set_scene (std::shared_ptr< scene::Scene > scene)
Definition at line 28 of file canvas.cc.
{
  this->scene_ = scene;
}
References scene(), and scene_.
Referenced by tiny_mesh_viewer::App::App().
Member Data Documentation
color_
glm::vec3 tiny_mesh_viewer::ui::Canvas::color_ private
Definition at line 29 of file canvas.h.
Referenced by ClearColor().
kDefaultColor
constexpr glm::vec3 tiny_mesh_viewer::ui::Canvas::kDefaultColor static constexpr private
Initial value:
=
      glm::vec3(0.0, 101.0 / 255.0, 179.0 / 255.0)
Definition at line 31 of file canvas.h.
Referenced by FromYAML().
scene_
std::shared_ptr<scene::Scene> tiny_mesh_viewer::ui::Canvas::scene_ private
Definition at line 28 of file canvas.h.
Referenced by Draw(), scene(), and set_scene().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/ui/canvas.h
tiny_mesh_viewer/ui/canvas.cc