tiny-mesh-viewer: tiny_mesh_viewer::scene::Scene Class Reference
tiny_mesh_viewer::scene::Scene Class Reference
#include <scene.h>
Public Member Functions
Scene (std::shared_ptr< Camera > camera=nullptr, std::shared_ptr< AmbientLight > ambient_light=nullptr, std::shared_ptr< PointLight > point_light=nullptr, const std::vector< std::shared_ptr< Object > > &objects={})
void Draw ()
Camera & camera ()
AmbientLight & ambient_light ()
PointLight & point_light ()
std::vector< std::shared_ptr< Object > > & objects ()
Static Public Member Functions
static std::shared_ptr< Scene > FromYAML (const YAML::Node &yaml)
Private Attributes
std::shared_ptr< Camera > camera_
std::shared_ptr< AmbientLight > ambient_light_
std::shared_ptr< PointLight > point_light_
std::vector< std::shared_ptr< Object > > objects_
Detailed Description
Definition at line 14 of file scene.h.
Constructor & Destructor Documentation
Scene()
tiny_mesh_viewer::scene::Scene::Scene (std::shared_ptr< Camera > camera = nullptr, std::shared_ptr< AmbientLight > ambient_light = nullptr, std::shared_ptr< PointLight > point_light = nullptr, const std::vector< std::shared_ptr< Object > > & objects = {}) explicit
Definition at line 14 of file scene.cc.
    : camera_(camera),
      ambient_light_(ambient_light),
      point_light_(point_light),
      objects_(objects) {}
Member Function Documentation
ambient_light()
AmbientLight & tiny_mesh_viewer::scene::Scene::ambient_light ()
Definition at line 30 of file scene.cc.
{ return *(this->ambient_light_); }
References ambient_light_.
Referenced by tiny_mesh_viewer::App::App().
camera()
Camera & tiny_mesh_viewer::scene::Scene::camera ()
Definition at line 28 of file scene.cc.
{ return *(this->camera_); }
References camera_.
Referenced by tiny_mesh_viewer::App::App().
Draw()
void tiny_mesh_viewer::scene::Scene::Draw ()
Definition at line 23 of file scene.cc.
                 {
  std::for_each(this->objects_.begin(), this->objects_.end(),
                [](std::shared_ptr<Object> object) -> void { object->Draw(); });
}
References objects_.
Referenced by tiny_mesh_viewer::ui::Canvas::Draw().
FromYAML()
std::shared_ptr< Scene > tiny_mesh_viewer::scene::Scene::FromYAML (const YAML::Node & yaml) static
Definition at line 38 of file scene.cc.
{
  if (!yaml.IsDefined()) {
    return std::make_shared<Scene>(std::make_shared<Camera>(),
                                   std::make_shared<AmbientLight>(),
                                   std::make_shared<PointLight>());
  }
  std::vector<std::shared_ptr<Object>> objects;
  if (yaml["objects"].IsDefined()) {
    std::transform(
        yaml["objects"].begin(), yaml["objects"].end(),
        /*result=*/std::back_inserter(objects),
        /*unary_op=*/[](const YAML::Node& yaml) -> std::shared_ptr<Object> {
          return Object::FromYAML(yaml);
        });
  }
  auto scene = std::make_shared<Scene>(
      Camera::FromYAML(yaml["camera"]),
      AmbientLight::FromYAML(yaml["ambient_light"]),
      PointLight::FromYAML(yaml["point_light"]), objects);
  return scene;
}
References tiny_mesh_viewer::scene::Camera::FromYAML(), tiny_mesh_viewer::scene::AmbientLight::FromYAML(), tiny_mesh_viewer::scene::PointLight::FromYAML(), tiny_mesh_viewer::scene::Object::FromYAML(), and objects().
Referenced by tiny_mesh_viewer::App::App().
objects()
std::vector< std::shared_ptr< Object > > & tiny_mesh_viewer::scene::Scene::objects ()
Definition at line 34 of file scene.cc.
{
  return this->objects_;
}
References objects_.
Referenced by FromYAML().
point_light()
PointLight & tiny_mesh_viewer::scene::Scene::point_light ()
Definition at line 32 of file scene.cc.
{ return *(this->point_light_); }
References point_light_.
Referenced by tiny_mesh_viewer::App::App().
Member Data Documentation
ambient_light_
std::shared_ptr<AmbientLight> tiny_mesh_viewer::scene::Scene::ambient_light_ private
Definition at line 32 of file scene.h.
Referenced by ambient_light().
camera_
std::shared_ptr<Camera> tiny_mesh_viewer::scene::Scene::camera_ private
Definition at line 31 of file scene.h.
Referenced by camera().
objects_
std::vector<std::shared_ptr<Object> > tiny_mesh_viewer::scene::Scene::objects_ private
Definition at line 34 of file scene.h.
Referenced by Draw(), and objects().
point_light_
std::shared_ptr<PointLight> tiny_mesh_viewer::scene::Scene::point_light_ private
Definition at line 33 of file scene.h.
Referenced by point_light().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/scene/scene.h
tiny_mesh_viewer/scene/scene.cc