tiny-mesh-viewer: tiny_mesh_viewer::opengl::Window Class Reference
tiny_mesh_viewer::opengl::Window Class Reference
#include <window.h>
Public Member Functions
Window (const int width=800, const int height=600, const std::string_view title="Tiny Mesh Viewer", GLFWmonitor *monitor=nullptr, GLFWwindow *share=nullptr)
~Window ()
glm::ivec2 FramebufferSize () const
int GetKey (int key)
void MakeContextCurrent ()
GLFWcursorposfun SetCursorPosCallback (GLFWcursorposfun callback)
GLFWframebuffersizefun SetFramebufferSizeCallback (GLFWframebuffersizefun callback)
void SetTitle (const std::string_view title)
void SetWindowUserPointer (void *pointer)
int ShouldClose ()
void SwapBuffers ()
Static Public Member Functions
static void Hint (const int hint, const int value)
Private Attributes
GLFWwindow * window_
Static Private Attributes
static constexpr int kContextVersionMajor = 3
static constexpr int kContextVersionMinor = 3
static constexpr int kOpenGLProfile = GLFW_OPENGL_CORE_PROFILE
Detailed Description
Definition at line 13 of file window.h.
Constructor & Destructor Documentation
Window()
tiny_mesh_viewer::opengl::Window::Window (const int width = 800, const int height = 600, const std::string_view title = "Tiny Mesh Viewer", GLFWmonitor * monitor = nullptr, GLFWwindow * share = nullptr) explicit
Definition at line 12 of file window.cc.
{
  Hint(/*hint=*/GLFW_CONTEXT_VERSION_MAJOR,
       /*value=*/kContextVersionMajor);
  Hint(/*hint=*/GLFW_CONTEXT_VERSION_MINOR,
       /*value=*/kContextVersionMinor);
  Hint(/*hint=*/GLFW_OPENGL_PROFILE,
       /*value=*/kOpenGLProfile);
#ifdef __APPLE__
  Hint(/*hint=*/GLFW_OPENGL_FORWARD_COMPAT, /*value=*/GL_TRUE);
#endif
  this->window_ = glfwCreateWindow(width, height, title.data(), monitor, share);
}
References Hint(), kContextVersionMajor, kContextVersionMinor, kOpenGLProfile, and window_.
~Window()
tiny_mesh_viewer::opengl::Window::~Window ()
Definition at line 27 of file window.cc.
{ glfwDestroyWindow(this->window_); }
References window_.
Member Function Documentation
FramebufferSize()
glm::ivec2 tiny_mesh_viewer::opengl::Window::FramebufferSize () const
Definition at line 29 of file window.cc.
{
  int width, height;
  glfwGetFramebufferSize(this->window_, &width, &height);
  return glm::ivec2(width, height);
}
References window_.
Referenced by tiny_mesh_viewer::scene::Camera::ConnectShader().
GetKey()
int tiny_mesh_viewer::opengl::Window::GetKey (int key)
Definition at line 35 of file window.cc.
{ return glfwGetKey(this->window_, key); }
References window_.
Referenced by tiny_mesh_viewer::scene::Camera::TrackMovement(), and tiny_mesh_viewer::scene::Camera::TrackRotation().
Hint()
void tiny_mesh_viewer::opengl::Window::Hint (const int hint, const int value) static
Definition at line 60 of file window.cc.
{
  glfwWindowHint(hint, value);
}
Referenced by Window().
MakeContextCurrent()
void tiny_mesh_viewer::opengl::Window::MakeContextCurrent ()
Definition at line 37 of file window.cc.
{ glfwMakeContextCurrent(this->window_); }
References window_.
Referenced by tiny_mesh_viewer::ui::Window::Init().
SetCursorPosCallback()
GLFWcursorposfun tiny_mesh_viewer::opengl::Window::SetCursorPosCallback (GLFWcursorposfun callback)
Definition at line 41 of file window.cc.
{
  return glfwSetCursorPosCallback(this->window_, callback);
}
References window_.
Referenced by tiny_mesh_viewer::ui::Window::Init().
SetFramebufferSizeCallback()
GLFWframebuffersizefun tiny_mesh_viewer::opengl::Window::SetFramebufferSizeCallback (GLFWframebuffersizefun callback)
Definition at line 45 of file window.cc.
{
  return glfwSetFramebufferSizeCallback(this->window_, callback);
}
References window_.
Referenced by tiny_mesh_viewer::ui::Window::Init().
SetTitle()
void tiny_mesh_viewer::opengl::Window::SetTitle (const std::string_view title)
Definition at line 50 of file window.cc.
{
  glfwSetWindowTitle(this->window_, title.data());
}
References window_.
SetWindowUserPointer()
void tiny_mesh_viewer::opengl::Window::SetWindowUserPointer (void * pointer)
Definition at line 54 of file window.cc.
{
  glfwSetWindowUserPointer(this->window_, pointer);
}
References window_.
Referenced by tiny_mesh_viewer::ui::Window::Init().
ShouldClose()
int tiny_mesh_viewer::opengl::Window::ShouldClose ()
Definition at line 39 of file window.cc.
{ return glfwWindowShouldClose(this->window_); }
References window_.
Referenced by tiny_mesh_viewer::ui::Window::Run().
SwapBuffers()
void tiny_mesh_viewer::opengl::Window::SwapBuffers ()
Definition at line 58 of file window.cc.
{ glfwSwapBuffers(this->window_); }
References window_.
Referenced by tiny_mesh_viewer::ui::Window::Run().
Member Data Documentation
kContextVersionMajor
constexpr int tiny_mesh_viewer::opengl::Window::kContextVersionMajor = 3 static constexpr private
Definition at line 36 of file window.h.
Referenced by Window().
kContextVersionMinor
constexpr int tiny_mesh_viewer::opengl::Window::kContextVersionMinor = 3 static constexpr private
Definition at line 37 of file window.h.
Referenced by Window().
kOpenGLProfile
constexpr int tiny_mesh_viewer::opengl::Window::kOpenGLProfile = GLFW_OPENGL_CORE_PROFILE static constexpr private
Definition at line 38 of file window.h.
Referenced by Window().
window_
GLFWwindow* tiny_mesh_viewer::opengl::Window::window_ private
Definition at line 34 of file window.h.
Referenced by FramebufferSize(), GetKey(), MakeContextCurrent(), SetCursorPosCallback(), SetFramebufferSizeCallback(), SetTitle(), SetWindowUserPointer(), ShouldClose(), SwapBuffers(), Window(), and ~Window().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/opengl/window.h
tiny_mesh_viewer/opengl/window.cc