tiny-mesh-viewer: tiny_mesh_viewer::shader::Shader Class Reference
tiny_mesh_viewer::shader::Shader Class Reference
#include <shader.h>
Public Member Functions
Shader ()=default
virtual ~Shader ()=default
Public Member Functions inherited from tiny_mesh_viewer::opengl::Program
Program ()
~Program ()
template<GLenum shader_type>
void AttachShader (const Shader< shader_type > &shader)
void Link ()
void Use ()
void Unuse ()
void UniformFloat (const std::string_view name, const float value)
void UniformMat4 (const std::string_view name, const glm::mat4 &value)
void UniformVec3 (const std::string_view name, const glm::vec3 &value)
float GetUniformFloat (const std::string_view name) const
glm::mat4 GetUniformMat4 (const std::string_view name) const
glm::vec3 GetUniformVec3 (const std::string_view name) const
Static Public Member Functions
static std::shared_ptr< Shader > FromYAML (const YAML::Node &yaml)
Detailed Description
Definition at line 12 of file shader.h.
Constructor & Destructor Documentation
Shader()
tiny_mesh_viewer::shader::Shader::Shader () explicit default
~Shader()
virtual tiny_mesh_viewer::shader::Shader::~Shader () virtual default
Member Function Documentation
FromYAML()
std::shared_ptr< Shader > tiny_mesh_viewer::shader::Shader::FromYAML (const YAML::Node & yaml) static
Definition at line 16 of file shader.cc.
{
  auto&& type = yaml["type"].as<std::string>();
  if (type == "Phong") {
    return Phong::FromYAML(yaml);
  } else if (type == "Gouraud") {
    return Gouraud::FromYAML(yaml);
  } else {
    throw common::Exception<std::runtime_error>(
        /*loc=*/common::source_loc::current(),
        /*what=*/"Unknown shader type: " + type);
  }
  return nullptr;
}
References tiny_mesh_viewer::shader::Gouraud::FromYAML(), and tiny_mesh_viewer::shader::Phong::FromYAML().
Referenced by tiny_mesh_viewer::App::App().
The documentation for this class was generated from the following files:
tiny_mesh_viewer/shader/shader.h
tiny_mesh_viewer/shader/shader.cc