name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Install Dependencies
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt install xorg-dev
          brew install doxygen graphviz
          ./vcpkg/bootstrap-vcpkg.sh
      - name: Generate Documentation
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          make docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/debug/documentation/html
